language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install mock
  - pip install pep8
  - pip install pyflakes
# command to run tests
before_script:
  - pep8 graphitepager
  - pep8 tests
  - pyflakes graphitepager
  - pyflakes tests
script: nosetests tests/*
